kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: docker.castive.dev
    repo: docker.castive.dev/castive-staging-redfox2
    tags: ${DRONE_COMMIT_SHA}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy
  image: quay.io/honestbee/drone-kubernetes
  settings:
    deployment: staging-redfox2
    repo: docker.castive.dev/castive-staging-redfox2
    tag: ${DRONE_COMMIT_SHA}
    container: redfox2
    namespace: default
    kubernetes_server: "https://10.0.1.30:6443"
    kubernetes_cert:
      from_secret: KUBERNETES_CERT
    kubernetes_token:
from_secret: KUBERNETES_TOKEN